services:
  api:
    container_name: linkService
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7071:7071"
    env_file:
      - link_server.env
